In [3]:
import numpy as np

In [6]:
x = 5
y = 1 / (1 + np.exp(-x))
print (y)

0.9933071490757153


In [20]:
array = np.linspace(1, 12, 12).reshape(3, 4)
print(array)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [23]:
array.sum(axis=1)

array([10., 26., 42.])

In [25]:
array[1,2]

7.0